<%--
  Created by IntelliJ IDEA.
  User: Administrator
  Date: 2019/2/26 0026
  Time: 18:12
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>测试</title>
</head>
<body>
欢迎
<div id="qrcode"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAIAAAAiOjnJAAAC+0lEQVR42u3d25GDMBBFQfJP2s6B
0p0H6hMAxlL7g0G1+/ykQI8lEFgCS2BJYAksgSWBJbAElgSWwBJYElgCS2BJYAksgSWBJbAElgSW
wBJYb67VWu6e313nnjUECyywwAILLLDAAgsssMA6u7inPiu3uO8+feMaggUWWGCBBRZYYIEFFlhg
zdzsU9uW+6yvriFYYIEFFlhggQUWWGCBBdaWRal8dV05pAALLLDAAgsssMACCyywwAIrtyi9h3rB
AgsssMACCyywwAILLLC+Dat3A3pHABvXECywwAILLLDAAgsssMACK/2gfqqN+OavIVhggQUWWGCB
BRZYYIEF1m0Vb8Bnl9ESgAUWWGCBBZbAAgus+2D1jhIMMhoPIoMFFlhggQUWWGCBBRZYYP2Sf3D2
1KJUHjLO3Y9xA1hggQUWWGCBBRZYYIG1F9a0I7yn6Pd+i2k/GLDAAgsssMACCyywwAILrPTg4GaO
xg1ggQUWWGCBBRZYYIEF1t5xQ45s7gG7dwSQ+6afmmOBBRZYYIEFFlhggQUWWEvGDdMe1HNbe/kA
AiywwAILLLDAAgsssMAC66n9J44bX29PG+KABRZYYIEFFlhggQUWWGBN2IDKK/dCrzzMXTy2AAss
sMACCyywwAILLLDAGng0uXeU8MRqZwQWWGCBBRZYYIEFFlhggTWwjUeccz/gxeMGsMACCyywwAIL
LLDAAmvtuKGy3LghN6SoHH8Uv6QHCyywwAILLLDAAgsssMB6ao8C567Ti7h9cAAWWGCBBRZYYIEF
FlhggRXdpI2P5d8ILLDAAgsssMACCyywwALrNljjnskPfXcvocECCyywwAILLLDAAgsssL6KeOOV
wQILLLDAAgsssMACCyyw0o/3p2BNGwGcuh+wwAILLLDAAgsssMACC6wJsHoP2ubGBNM2+7qX0GCB
BRZYYIEFFlhggQXWSFgSWAJLYElgCSyBJYElsASWBJbAElgCSwJLYAksCSyBJbAksASWwJLAEli6
sD+liYW159UufAAAAABJRU5ErkJggg=="></div>
</body>
</html>
