<%--
  Created by IntelliJ IDEA.
  User: Administrator
  Date: 2019/2/26 0026
  Time: 18:12
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>测试</title>
</head>
<body>
欢迎
<div id="qrcode"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAIAAAAiOjnJAAADe0lEQVR42u3bW3KDMBAAwdz/0skV
TNgRMur5TCWER7tKXuDnVwr6cQoElsASWBJYAktgSWAJLIElgSWwBJYElsASWBJYAktgSWAJLIEl
gSWwBJYElsASWBJYAktgSWAJLIE182+Crv7fT35+dTtXj7HYZnHewAILLLDAAgus74NVbKcA9Mk2
r/5OAXrldsACCyywwAILrO+AVSx4d9ifYvG+w3kDCyywwAILLLDOgnVnO/Vgc7fjBQsssMACCyyw
wJq8qPV+Xh2EggUWWGCBBRZYYFWw6gtf4KgfElx53sACCyywwAILrPfAKl4KOOHnXqYACyywwAIL
LLCerDi57xtgggUWWGCBBRZYpy/e72yn2IcC4sovBGCBBRZYYIEF1jsX7ysP+M5N66sfknqwWewn
WGCBBRZYYIEF1urB48oLM/XyxdGTd7DAAgsssMA6EFb9ksLUCw7FYnmHBxXBAgsssMACC6z3wyoG
j3dw1C90rBzMHr14BwsssMACCyyw/r2gLgAVQ9odQB9xExossMACCyywwEoX7/WLDyvRPzVwBgss
sMACCyywLN6fXJivPPbid8ACCyywwAILrHfCmhoGTi3wi9+pL/z+yMACCyywwAILrEeXeEOL5eIB
wPoD4yY0WGCBBRZYYIG1GtDUA3R3hrHFxSgW/m5CgwUWWGCBBRZYTw426w/A1LHXg1OwwAILLLDA
AussWFML1XqouMOXAy9TgAUWWGCBBRZY1YWcuolbg64fMJwaLIMFFlhggQUWWO+BNXWB6y8KxYOH
UyD2wQQWWGCBBRZYYO0Iq76RXGBa+aLE1EOOYIEFFlhggQXWuYv3lYvxeohaQ9wTHFhggQUWWGCB
9YbqlxGKBXgxgN3noT+wwAILLLDAAmv1hd9hkDj1RaE4J3e+KBx9ExossMACCyywDoe1cjtTyKZw
FDfawQILLLDAAgsssP4zPLyzmK2/TNw53h32ByywwAILLLDAAqsaGBYvX0wt/KfgWryDBRZYYIEF
FlgVrGL4ufJv630GCyywwAILLLDeA6sAOjU4LQawU7gt3sECCyywwAILrE9P0NTLFFP7MLWgXvkB
2AcZWGCBBRZYYIElgSWwBJYElsASWBJYAktgSWAJLIElgSWwBJYElsASWBJYAktgSWAJLIElgSWw
BJYElsASWBJYAktgSZf7A4sW+OdNyxhXAAAAAElFTkSuQmCC"></div>
</body>
</html>
